application: right-cdn
version: 1_0_0
runtime: python
api_version: 1

handlers:
# the index page routes
- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: 1d

- url: /index.html
  static_files: static/index.html
  upload: static/index.html
  expiration: 1d

- url: /index.css
  static_files: static/index.css
  upload: static/index.css
  expiration: 1d

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 365d


# the core files serving routes
- url: /([^\d\/]+\.js)
  static_files: builds/core/\1
  upload: builds/core/(.*)
  expiration: 10d

- url: /([^\/]+\-\d+\.\d+\.\d+\.js)
  static_files: builds/core/\1
  upload: builds/core/(.*)
  expiration: 365d


# the plugin serving routes
- url: /plugins/(.*\-\d+\.\d+\.\d+\.js)
  static_files: builds/plugins/\1
  upload: builds/plugins/(.*)
  expiration: 10d

- url: /plugins/([^\d]+\.js)
  static_files: builds/plugins/\1
  upload: builds/plugins/(.*)
  expiration: 365d


# UI module serving routes
- url: /ui/(.*\-\d+\.\d+\.\d+\.js)
  static_files: builds/ui/\1
  upload: builds/ui/(.*)
  expiration: 10d

- url: /ui/([^\d]+\.js)
  static_files: builds/ui/\1
  upload: builds/ui/(.*)
  expiration: 365d


# i18n module routes
- url: /i18n/(.*)
  static_files: builds/i18n/\1
  upload: builds/i18n/(.*)
  expiration: 10d